# -*- coding: utf-8 -*-
"""1st test.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QXZqY4I4bMGVGywHedPgZvrDNf4QBByz
"""

# ============================================================
# VARIABLES
# ============================================================

# 1. Create a variable called name and assign your name to it
name = "Alice"
print(name)

# 2. Swap two variables
a = 10
b = 20
a, b = b, a
print(a, b)

# 3. Three variables in a single line
x, y, z = 1, 2, 3
print(x + y + z)

# 4. Reassign variable
value = 100
print(value)
value = 200
print(value)

# 5. Delete a variable
num = 50
del num
try:
    print(num)
except NameError as e:
    print("Error:", e)


# ============================================================
# DATA TYPES
# ============================================================

# 1. One variable of each type
i = 10
f = 3.14
s = "Hello"
b = True
print(i, type(i))
print(f, type(f))
print(s, type(s))
print(b, type(b))

# 2. Check data types
print(type(3.14))
print(type("Hello"))
print(type(True))
print(type(0))

# 3. Check if x is an integer
x = 9
print(isinstance(x, int))

# 4. Data type of None
print(type(None))

# 5. Large integer and small float
large = 999999999999999999999
small = 0.000000000001
print(large)
print(small)


# ============================================================
# TYPE CONVERSION
# ============================================================

# 1. String to integer
result = int("123") + 7
print(result)

# 2. Float to integer
print(int(9.99))

# 3. Integer to boolean
print(bool(0))
print(bool(1))

# 4. Boolean to integer
print(int(True))
print(int(False))

# 5. Input to float and multiply
num = float(input("Enter a number: "))
print(num * 2)

# 6. Invalid string to integer
try:
    print(int("hello"))
except ValueError as e:
    print("Error:", e)


# ============================================================
# STRING MANIPULATION
# ============================================================

# 1. Uppercase and lowercase
text = "Hello, World!"
print(text.upper())
print(text.lower())

# 2. Length of string
print(len("Python Programming"))

# 3. Extract "World" using slicing
text = "Hello, World!"
print(text[7:12])

# 4. Reverse a string
print("abcdef"[::-1])

# 5. Check if "nan" is in "banana"
print("nan" in "banana")

# 6. Replace word
print("This is a bad day".replace("bad", "good"))

# 7. Strip whitespace
print("   hello   ".strip())

# 8. Split string by comma
print("apple,banana,cherry".split(","))

# 9. Count occurrences
print("banana".count("a"))

# 10. Check alphanumeric
print("Python123".isalnum())


# ============================================================
# STRING FORMATTING
# ============================================================

# 1. f-string with name and age
name = "John"
age = 25
print(f"My name is {name} and I am {age} years old")

# 2. .format() for price
print("The price is {:.2f} dollars".format(49.99))

# 3. Float to 2 decimal places
print(f"{3.14159:.2f}")

# 4. Leading zeros
print(f"{7:03d}")

# 5. Multiplication table line
print(f"5 x 3 = {5 * 3}")

# 6. Aligned text with padding
print(f"{'Name':<10} {'Score':<5}")
print(f"{'Alice':<10} {95:<5}")
print(f"{'Bob':<10} {88:<5}")
print(f"{'Charlie':<10} {72:<5}")


# ============================================================
# PYTHON LISTS
# ============================================================

# 1. List of 5 fruits
fruits = ["apple", "banana", "cherry", "mango", "grape"]
print(fruits)

# 2. First and last element
lst = [10, 20, 30, 40, 50]
print(lst[0])
print(lst[-1])

# 3. Append element
lst.append(60)
print(lst)

# 4. Insert 99 at index 2
lst.insert(2, 99)
print(lst)

# 5. Remove "banana"
fruits.remove("banana")
print(fruits)

# 6. Sort ascending and descending
nums = [5, 2, 8, 1, 9]
print(sorted(nums))
print(sorted(nums, reverse=True))

# 7. Length, max, min
lst2 = [3, 7, 1, 9, 4]
print(len(lst2))
print(max(lst2))
print(min(lst2))

# 8. Slice to get [2, 3, 4]
lst3 = [0, 1, 2, 3, 4, 5, 6]
print(lst3[2:5])

# 9. Copy list without affecting original
original = [1, 2, 3, 4, 5]
copy = original.copy()
copy.append(99)
print("Original:", original)
print("Copy:", copy)

# 10. Merge two lists
list1 = [1, 2, 3]
list2 = [4, 5, 6]
merged = list1 + list2
print(merged)